[package]
name = "owoof"
version = "0.1.1"
authors = ["sqwishy <somebody@froghat.ca>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/sqwishy/owoof"
homepage = "https://github.com/sqwishy/owoof"
description = "Uses SQLite to store data and a datalog-like format to query it. "
keywords = ["datalog", "sqlite"]

[[bin]]
name = "cli"
required-features = ["cli"]

[features]
cli = ["serde_json"]

[dependencies]
serde = { version =  "1", features = ["derive"] }
anyhow = "1"             # Flexible concrete Error type built on std::error::Error
thiserror = "1"          # derive(Error)
rusqlite = { version = "0.23", features = ["uuid", "functions"] }

either = "1"                   # The enum `Either` with variants `Left` and `Right` is a general purpose sum type with two ca…

uuid = { version = "0.8", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }

serde_json = { version = "1", optional = true }

[dev-dependencies]
csv = "1"
serde_json = "1"
