[package]
name = "oof"
version = "0.1.0"
authors = ["sqwishy <somebody@froghat.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version =  "1", features = ["derive"] }
anyhow = "1"             # Flexible concrete Error type built on std::error::Error
thiserror = "1"          # derive(Error)
rusqlite = { version = "0.21", features = ["uuid", "functions"] }

either = "1.5"                   # The enum `Either` with variants `Left` and `Right` is a general purpose sum type with two ca…

# serde_json = "1"
# serde_cbor = "0.10"
# erased-serde = "0.3"         # Type-erased Serialize and Serializer traits

uuid = { version = "0.8", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }

# lazy_static = "1"
# regex = "1"

[dev-dependencies]
csv = "1"
serde_json = "1"
